alias editBashProfile='code ~/Desktop/Folders/coding-bootcamp-projects/BashProfile/profile.sh'
alias ebp='editBashProfile'
alias refreshBashProfile='source ~/Desktop/Folders/coding-bootcamp-projects/BashProfile/profile.sh'
alias rbp='refreshBashProfile'
alias projects='cd ~/Desktop/Folders/coding-bootcamp-projects'
alias cdbp='cd ~/Desktop/Folders/coding-bootcamp-projects/BashProfile'